project_id = "zqslnunbarqnbbnkmyax"

[functions.export-session]
verify_jwt = false

[functions.generate-group-rotation]
verify_jwt = false

[functions.reset-group]
verify_jwt = false

[functions.reset-session]
verify_jwt = false

[functions.reset-ungrouped-court]
verify_jwt = false
