from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text()
    if old not in text:
        raise RuntimeError(f"Expected block not found in {path}: {old[:120]!r}")
    p.write_text(text.replace(old, new, 1))


# AdminGroup: canonical display court numbers + session-scoped state + atomic RPCs.
path = "src/pages/admin/AdminGroup.tsx"
replace_once(
    path,
    '''  const courtNumbers: number[] = (group?.court_ids?.length ? group.court_ids : null)\n    || groupCourtUnit?.group_court_numbers\n    || [];''',
    '''  // Display court numbers come from the session-scoped court unit. court_groups.court_ids\n  // contains database court PKs and must never be treated as display numbers.\n  const courtNumbers: number[] = groupCourtUnit?.group_court_numbers\n    || (group?.court_ids?.length ? group.court_ids.map((_: number, i: number) => i + 1) : []);''',
)
replace_once(
    path,
    '''    queryKey: ["group_court_state", groupId],\n    queryFn: async () => {\n      const { data, error } = await supabase\n        .from("group_court_state" as any)\n        .select("*")\n        .eq("group_id", groupId!);''',
    '''    queryKey: ["group_court_state", groupId, sessionId],\n    queryFn: async () => {\n      let stateQuery = supabase\n        .from("group_court_state" as any)\n        .select("*")\n        .eq("group_id", groupId!);\n      if (sessionId) stateQuery = stateQuery.eq("session_id", sessionId);\n      const { data, error } = await stateQuery;''',
)
old_start = '''  // Start match on a panel\n  const startMatchOnPanel = useMutation({\n    mutationFn: async ({ courtNumber, matchId }: { courtNumber: number; matchId: string }) => {\n      const match = matches.find(m => m.id === matchId);\n      if (!match) throw new Error("Match not found");\n\n      // Check no player in this match is currently playing elsewhere\n      const playerIds = [match.team1_player1_id, match.team1_player2_id, match.team2_player1_id, match.team2_player2_id].filter(Boolean);\n      const liveMatches = matches.filter(m => m.status === "in_progress" && m.id !== matchId);\n      for (const lm of liveMatches) {\n        const livePlayerIds = [lm.team1_player1_id, lm.team1_player2_id, lm.team2_player1_id, lm.team2_player2_id];\n        for (const pid of playerIds) {\n          if (livePlayerIds.includes(pid)) {\n            throw new Error(`${getPlayerName(pid)} is currently playing on another court`);\n          }\n        }\n      }\n\n      // Update match to in_progress\n      const { error: matchErr } = await supabase\n        .from("matches")\n        .update({ status: "in_progress", started_at: new Date().toISOString() })\n        .eq("id", matchId)\n        .eq("status", "pending");\n      if (matchErr) throw matchErr;\n\n      // Update group_court_state\n      const { error: stateErr } = await supabase\n        .from("group_court_state" as any)\n        .update({\n          current_match_id: matchId,\n          current_match_global_index: match.global_match_index,\n          is_live: true,\n          updated_at: new Date().toISOString(),\n        } as any)\n        .eq("group_id", groupId!)\n        .eq("court_number", courtNumber);\n      if (stateErr) throw stateErr;\n    },'''
new_start = '''  // Start match on a panel atomically on the server. The RPC re-checks player\n  // concurrency inside the same DB transaction, so simultaneous admins cannot race.\n  const startMatchOnPanel = useMutation({\n    mutationFn: async ({ courtNumber, matchId }: { courtNumber: number; matchId: string }) => {\n      if (!sessionId || !groupId) throw new Error("Active session and group are required");\n      const { data, error } = await supabase.rpc("start_group_match_atomic" as any, {\n        p_session_id: sessionId,\n        p_group_id: groupId,\n        p_court_number: courtNumber,\n        p_match_id: matchId,\n      } as any);\n      if (error) throw error;\n      const result = data as any;\n      if (!result?.ok) throw new Error(result?.error || "Could not start match");\n      return result;\n    },'''
replace_once(path, old_start, new_start)
old_end = '''  // End match on a panel\n  const endMatchOnPanel = useMutation({\n    mutationFn: async ({ courtNumber, matchId, team1Score, team2Score }: {\n      courtNumber: number; matchId: string; team1Score: number; team2Score: number;\n    }) => {\n      const { error: matchErr } = await supabase\n        .from("matches")\n        .update({\n          status: "completed",\n          team1_score: team1Score,\n          team2_score: team2Score,\n          completed_at: new Date().toISOString(),\n        })\n        .eq("id", matchId);\n      if (matchErr) throw matchErr;\n\n      const { error: stateErr } = await supabase\n        .from("group_court_state" as any)\n        .update({\n          current_match_id: null,\n          current_match_global_index: null,\n          is_live: false,\n          updated_at: new Date().toISOString(),\n        } as any)\n        .eq("group_id", groupId!)\n        .eq("court_number", courtNumber);\n      if (stateErr) throw stateErr;\n    },'''
new_end = '''  // End match on a panel atomically on the server. Match score + court state\n  // commit together or not at all.\n  const endMatchOnPanel = useMutation({\n    mutationFn: async ({ courtNumber, matchId, team1Score, team2Score }: {\n      courtNumber: number; matchId: string; team1Score: number; team2Score: number;\n    }) => {\n      if (!sessionId || !groupId) throw new Error("Active session and group are required");\n      const { data, error } = await supabase.rpc("end_group_match_atomic" as any, {\n        p_session_id: sessionId,\n        p_group_id: groupId,\n        p_court_number: courtNumber,\n        p_match_id: matchId,\n        p_team1_score: team1Score,\n        p_team2_score: team2Score,\n      } as any);\n      if (error) throw error;\n      const result = data as any;\n      if (!result?.ok) throw new Error(result?.error || "Could not end match");\n      return result;\n    },'''
replace_once(path, old_end, new_end)

# PersonalRoster: remove the final legacy cross-session rank-popup key.
replace_once(
    "src/components/public/PersonalRoster.tsx",
    '''      const shownKey = `gp_rank_popup_${courtId}_${selectedPlayerId}`;''',
    '''      const shownKey = `${storagePrefix}_rank_popup_${selectedPlayerId}`;''',
)

# Group generator: never interpret court_groups.court_ids as display numbers and reuse
# the session's real court row when building canonical membership.
path = "supabase/functions/generate-group-rotation/index.ts"
replace_once(
    path,
    '''    let courtNumbers: number[] = group.court_ids || [];\n\n    if (courtNumbers.length === 0) {\n      const { data: courtUnit } = await supabase\n        .from("court_units")\n        .select("group_court_numbers")\n        .eq("court_group_id", groupId)\n        .maybeSingle();\n\n      if (courtUnit?.group_court_numbers) {\n        courtNumbers = courtUnit.group_court_numbers;\n      }\n    }''',
    '''    // Resolve display court numbers from canonical/session-scoped metadata.\n    // court_groups.court_ids contains DB court PKs, not display numbers.\n    let courtNumbers: number[] = [];\n    const { data: courtUnit } = await supabase\n      .from("court_units")\n      .select("group_court_numbers")\n      .eq("court_group_id", groupId)\n      .eq("session_id", sessionId || group.session_id)\n      .maybeSingle();\n\n    if (courtUnit?.group_court_numbers?.length) {\n      courtNumbers = courtUnit.group_court_numbers;\n    } else {\n      const { data: existingMembers } = await supabase\n        .from("group_physical_courts")\n        .select("court_number")\n        .eq("group_id", groupId)\n        .eq("session_id", sessionId || group.session_id)\n        .order("court_number", { ascending: true });\n      if (existingMembers?.length) {\n        courtNumbers = existingMembers.map((m: any) => m.court_number);\n      } else if (group.court_ids?.length) {\n        // Compatibility only for pre-normalization groups: preserve court count without\n        // leaking database PK values into display/queue semantics.\n        courtNumbers = group.court_ids.map((_: number, i: number) => i + 1);\n      }\n    }''',
)
replace_once(
    path,
    '''      } else {\n        // Create a new courts row for this group physical court\n        const { data: newCourt, error: courtErr } = await supabase\n          .from("courts")\n          .insert({\n            name: `Group Court ${cn}`,\n            session_id: effectiveSessionId,\n          })\n          .select("id")\n          .single();\n\n        if (courtErr || !newCourt) {\n          return errorResponse("precheck", `Failed to create court entry for court ${cn}`, courtErr?.message);\n        }\n\n        // Create mapping row\n        const { error: mapErr } = await supabase\n          .from("group_physical_courts")\n          .insert({\n            group_id: groupId,\n            court_number: cn,\n            court_id: newCourt.id,\n            session_id: effectiveSessionId,\n          });\n\n        if (mapErr) {\n          return errorResponse("precheck", `Failed to create court mapping for court ${cn}`, mapErr.message);\n        }\n\n        courtIdMap[cn] = newCourt.id;\n      }''',
    '''      } else {\n        // Reuse the real physical court already created for this session by SetupWizard.\n        // Only create a compatibility court when migrating an old group lacking that unit.\n        const { data: physicalUnit } = await supabase\n          .from("court_units")\n          .select("court_id")\n          .eq("session_id", effectiveSessionId)\n          .eq("type", "court")\n          .eq("court_number", cn)\n          .maybeSingle();\n\n        let physicalCourtId = physicalUnit?.court_id || null;\n        if (!physicalCourtId) {\n          const { data: newCourt, error: courtErr } = await supabase\n            .from("courts")\n            .insert({\n              name: `Group Court ${cn}`,\n              session_id: effectiveSessionId,\n            })\n            .select("id")\n            .single();\n          if (courtErr || !newCourt) {\n            return errorResponse("precheck", `Failed to create court entry for court ${cn}`, courtErr?.message);\n          }\n          physicalCourtId = newCourt.id;\n        }\n\n        const { error: mapErr } = await supabase\n          .from("group_physical_courts")\n          .upsert({\n            group_id: groupId,\n            court_number: cn,\n            court_id: physicalCourtId,\n            session_id: effectiveSessionId,\n          }, { onConflict: "group_id,court_number,session_id" });\n\n        if (mapErr) {\n          return errorResponse("precheck", `Failed to create court mapping for court ${cn}`, mapErr.message);\n        }\n\n        courtIdMap[cn] = physicalCourtId;\n      }''',
)

print("Foundation hardening 3 patch applied")
