/**
 * Admin scheduling screen.
 *
 * Thursdays are generated by recurring schedules (rolling window of DRAFT
 * sessions + exact Shopify links). Socials are created here by hand. Nothing on
 * this page starts scoring — that is still the event-day Start Session control.
 */
import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import PageLayout from "@/components/layout/PageLayout";
import GlobalHeader from "@/components/layout/GlobalHeader";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ChevronLeft, RefreshCw, CalendarPlus, Pause, Play, Undo2, X } from "lucide-react";
import { toast } from "sonner";
import { useAdminAuth } from "@/hooks/useAdminAuth";
import { useEventContext } from "@/hooks/useEventContext";
import { useEventCatalog } from "@/hooks/useEventCatalog";
import {
  pinSession,
  todayIsoDate,
  useRecurringSchedules,
  useScheduleExceptions,
  useScheduleMutations,
  useUpcomingSessions,
  type ScheduleRow,
  type UpcomingSession,
} from "@/hooks/useSchedules";

const WEEKDAY_NAMES = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

const formatDate = (iso: string) =>
  new Date(`${iso}T12:00:00`).toLocaleDateString("en-US", {
    weekday: "short",
    day: "numeric",
    month: "short",
    year: "numeric",
  });

const statusTone: Record<string, string> = {
  draft: "bg-muted text-muted-foreground border-border",
  live: "bg-primary/15 text-primary border-primary/30",
  ended: "bg-secondary text-muted-foreground border-border",
};

const AdminSchedule = () => {
  const navigate = useNavigate();
  const { isAdmin, isLoading } = useAdminAuth();
  const { cities, locations, setSelectedCityId, setSelectedEventId, setSelectedLocationId } =
    useEventContext();

  useEffect(() => {
    if (!isLoading && !isAdmin) navigate("/admin/login");
  }, [isLoading, isAdmin, navigate]);

  const { data: schedules = [] } = useRecurringSchedules();
  const { data: exceptions = [] } = useScheduleExceptions();
  const { data: thursdays = [], isLoading: thursdaysLoading } = useUpcomingSessions("thursdays");
  const { data: socials = [] } = useUpcomingSessions("social");
  const { reconcile, setScheduleActive, skipDate, unskipDate, setCapacity, createSocial } =
    useScheduleMutations();

  // Locality / city names for every schedule, independent of the picked scope.
  const { data: places } = useQuery({
    queryKey: ["schedule_places"],
    queryFn: async () => {
      const [c, l] = await Promise.all([
        supabase.from("cities").select("id, name"),
        supabase.from("locations").select("id, name, city_id"),
      ]);
      if (c.error) throw c.error;
      if (l.error) throw l.error;
      return { cities: c.data ?? [], locations: l.data ?? [] };
    },
  });

  const cityName = (id: string | null) =>
    places?.cities.find((c) => c.id === id)?.name ?? cities.find((c) => c.id === id)?.name ?? "—";
  const localityName = (id: string | null) =>
    id
      ? places?.locations.find((l) => l.id === id)?.name ??
        locations.find((l) => l.id === id)?.name ??
        "—"
      : null;

  const scheduleFor = (session: UpcomingSession): ScheduleRow | undefined =>
    schedules.find(
      (s) =>
        s.id === session.recurring_schedule_id ||
        (s.city_id === session.city_id && s.location_id === session.location_id),
    );

  /**
   * Pin the exact session and take the admin into the normal dashboard for it.
   *
   * Resolves the event directly from the `events` table for the session's own
   * city — the context `events` list may still be scoped to a previously
   * selected city, so reusing it here can pin a foreign/stale event id.
   */
  const openSession = async (session: UpcomingSession) => {
    const { data: eventRows, error } = await supabase
      .from("events")
      .select("id")
      .eq("city_id", session.city_id)
      .eq("event_type", sessionEventFilterType(session))
      .eq("active", true);
    if (error) {
      toast.error("Could not load events for this session's city.");
      return;
    }
    const target = resolveSessionTargetEvent(session, eventRows ?? []);
    if ("error" in target) {
      // Never guess: show the problem instead of pinning a wrong event.
      toast.error(
        target.error === "none"
          ? "No active event found for this session's city."
          : "More than one active event found for this city — resolve it on the home screen first.",
      );
      return;
    }
    setSelectedCityId(session.city_id);
    setSelectedEventId(target.eventId);
    setSelectedLocationId(session.event_type === "social" ? null : session.location_id);
    pinSession(session.id);
    navigate("/admin");
  };

  const [capacityDrafts, setCapacityDrafts] = useState<Record<string, string>>({});

  const saveCapacity = (session: UpcomingSession) => {
    const raw = (capacityDrafts[session.id] ?? "").trim();
    if (raw === "") {
      setCapacity.mutate({ sessionId: session.id, capacity: null });
      return;
    }
    const value = Number(raw);
    if (!Number.isInteger(value) || value <= 0) {
      toast.error("Capacity must be a whole number above zero, or empty for no limit.");
      return;
    }
    setCapacity.mutate({ sessionId: session.id, capacity: value });
  };

  // ---- Social creation form ----
  const socialCatalog = useEventCatalog("social");
  const socialProduct = socialCatalog.data?.products[0];
  const [socialCity, setSocialCity] = useState("");
  const [socialDate, setSocialDate] = useState("");
  const [socialCapacity, setSocialCapacity] = useState("");
  const [socialVariants, setSocialVariants] = useState<string[]>([]);

  useEffect(() => {
    if (!socialCity && cities.length > 0) setSocialCity(cities[0].id);
  }, [cities, socialCity]);

  const toggleVariant = (variantId: string) =>
    setSocialVariants((prev) =>
      prev.includes(variantId) ? prev.filter((v) => v !== variantId) : [...prev, variantId],
    );

  const submitSocial = () => {
    if (!socialCity || !socialDate) {
      toast.error("Pick a city and a date.");
      return;
    }
    if (!socialProduct) {
      toast.error("Social ticket types are still loading.");
      return;
    }
    if (socialVariants.length === 0) {
      toast.error("Select at least one ticket type.");
      return;
    }
    const capacity = socialCapacity.trim() === "" ? null : Number(socialCapacity);
    if (capacity !== null && (!Number.isInteger(capacity) || capacity <= 0)) {
      toast.error("Capacity must be a whole number above zero.");
      return;
    }
    createSocial.mutate(
      {
        cityId: socialCity,
        date: socialDate,
        productId: socialProduct.productId,
        variantIds: socialVariants,
        capacity,
      },
      {
        onSuccess: () => {
          setSocialDate("");
          setSocialCapacity("");
          setSocialVariants([]);
        },
      },
    );
  };

  const thursdaysByDate = useMemo(() => {
    const map = new Map<string, UpcomingSession[]>();
    for (const session of thursdays) {
      map.set(session.date, [...(map.get(session.date) ?? []), session]);
    }
    return [...map.entries()].sort((a, b) => (a[0] < b[0] ? -1 : 1));
  }, [thursdays]);

  const today = todayIsoDate();

  const sessionRow = (session: UpcomingSession) => {
    const schedule = scheduleFor(session);
    const locked = session.registrations > 0 || session.status !== "draft";
    return (
      <div
        key={session.id}
        className="flex flex-col gap-2 border-t border-border/60 py-3 first:border-t-0 sm:flex-row sm:items-center sm:justify-between"
      >
        <div className="min-w-0">
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-sm font-medium">
              {localityName(session.location_id) ?? cityName(session.city_id)}
            </span>
            <Badge variant="outline" className={`text-[10px] ${statusTone[session.status]}`}>
              {session.status}
            </Badge>
            <Badge
              variant="outline"
              className={`text-[10px] ${
                session.shopifyLinked
                  ? "border-primary/30 text-primary"
                  : "border-destructive/40 text-destructive"
              }`}
            >
              {session.shopifyLinked ? "On sale" : "Not linked"}
            </Badge>
            {session.soldOut && (
              <Badge variant="outline" className="text-[10px] border-destructive/40 text-destructive">
                Full
              </Badge>
            )}
          </div>
          <p className="mt-1 text-[11px] text-muted-foreground">
            {session.booked} booked
            {session.capacity !== null
              ? ` · ${session.remaining} of ${session.capacity} left`
              : " · no capacity limit"}
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <Input
            value={capacityDrafts[session.id] ?? (session.capacity?.toString() ?? "")}
            onChange={(e) =>
              setCapacityDrafts((prev) => ({ ...prev, [session.id]: e.target.value }))
            }
            placeholder="Seats"
            inputMode="numeric"
            className="h-8 w-20 text-xs"
          />
          <Button
            size="sm"
            variant="outline"
            className="h-8 text-xs"
            onClick={() => saveCapacity(session)}
            disabled={setCapacity.isPending}
          >
            Save
          </Button>
          <Button size="sm" className="h-8 text-xs" onClick={() => openSession(session)}>
            Open
          </Button>
          {schedule && session.date >= today && (
            <Button
              size="sm"
              variant="ghost"
              className="h-8 gap-1 text-xs text-muted-foreground"
              disabled={skipDate.isPending}
              onClick={() =>
                locked
                  ? toast.error(
                      "This date already has registrations or event-day setup. Handle those seats before skipping.",
                    )
                  : skipDate.mutate({ scheduleId: schedule.id, date: session.date })
              }
            >
              <X className="h-3 w-3" />
              Skip
            </Button>
          )}
        </div>
      </div>
    );
  };

  if (isLoading || !isAdmin) return null;

  return (
    <PageLayout>
      <GlobalHeader />
      <div className="mx-auto w-full max-w-3xl px-4 py-6">
        <div className="mb-4 flex items-center justify-between gap-2">
          <Button variant="ghost" size="sm" className="gap-1 text-xs" onClick={() => navigate("/admin")}>
            <ChevronLeft className="h-4 w-4" />
            Dashboard
          </Button>
          <Button
            size="sm"
            variant="outline"
            className="h-8 gap-1.5 text-xs"
            disabled={reconcile.isPending}
            onClick={() => reconcile.mutate(undefined)}
          >
            <RefreshCw className={`h-3 w-3 ${reconcile.isPending ? "animate-spin" : ""}`} />
            Reconcile now
          </Button>
        </div>

        <h1 className="text-xl font-semibold tracking-tight">Schedule</h1>
        <p className="mt-1 text-xs text-muted-foreground">
          Future dates are created as drafts and put on sale automatically. Scoring only goes live when
          you press Start Session on the event day.
        </p>

        <Tabs defaultValue="thursdays" className="mt-5">
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger value="thursdays">Thursdays</TabsTrigger>
            <TabsTrigger value="social">Social</TabsTrigger>
          </TabsList>

          <TabsContent value="thursdays" className="mt-4 space-y-4">
            {schedules.length === 0 && (
              <Card className="p-4 text-sm text-muted-foreground">
                No recurring schedule yet.
              </Card>
            )}
            {schedules.map((schedule) => {
              const skipped = exceptions.filter((e) => e.schedule_id === schedule.id && e.skipped);
              return (
                <Card key={schedule.id} className="p-4">
                  <div className="flex flex-wrap items-center justify-between gap-2">
                    <div>
                      <p className="text-sm font-medium">
                        {cityName(schedule.city_id)} · {localityName(schedule.location_id)}
                      </p>
                      <p className="text-[11px] text-muted-foreground">
                        Every {WEEKDAY_NAMES[schedule.weekday]} · {schedule.horizon_weeks} weeks ahead ·
                        variant {schedule.shopify_variant_id}
                      </p>
                      {schedule.last_error && (
                        <p className="mt-1 text-[11px] text-destructive">{schedule.last_error}</p>
                      )}
                    </div>
                    <div className="flex items-center gap-2">
                      <Badge
                        variant="outline"
                        className={`text-[10px] ${
                          schedule.is_active
                            ? "border-primary/30 text-primary"
                            : "border-border text-muted-foreground"
                        }`}
                      >
                        {schedule.is_active ? "Active" : "Paused"}
                      </Badge>
                      <Button
                        size="sm"
                        variant="ghost"
                        className="h-8 gap-1 text-xs"
                        disabled={setScheduleActive.isPending}
                        onClick={() =>
                          setScheduleActive.mutate({
                            scheduleId: schedule.id,
                            active: !schedule.is_active,
                          })
                        }
                      >
                        {schedule.is_active ? (
                          <>
                            <Pause className="h-3 w-3" /> Pause
                          </>
                        ) : (
                          <>
                            <Play className="h-3 w-3" /> Resume
                          </>
                        )}
                      </Button>
                    </div>
                  </div>

                  {skipped.length > 0 && (
                    <div className="mt-3 space-y-1">
                      {skipped.map((exception) => (
                        <div
                          key={exception.id}
                          className="flex items-center justify-between rounded-md bg-muted/50 px-2 py-1"
                        >
                          <span className="text-[11px] text-muted-foreground">
                            Skipped · {formatDate(exception.date)}
                          </span>
                          <Button
                            size="sm"
                            variant="ghost"
                            className="h-7 gap-1 text-[11px]"
                            disabled={unskipDate.isPending}
                            onClick={() =>
                              unskipDate.mutate({ scheduleId: schedule.id, date: exception.date })
                            }
                          >
                            <Undo2 className="h-3 w-3" />
                            Undo skip
                          </Button>
                        </div>
                      ))}
                    </div>
                  )}
                </Card>
              );
            })}

            <Card className="p-4">
              <h2 className="text-sm font-medium">Upcoming dates</h2>
              {thursdaysLoading && (
                <p className="mt-2 text-xs text-muted-foreground">Loading…</p>
              )}
              {!thursdaysLoading && thursdaysByDate.length === 0 && (
                <p className="mt-2 text-xs text-muted-foreground">
                  Nothing scheduled yet — press Reconcile now.
                </p>
              )}
              <div className="mt-2 space-y-4">
                {thursdaysByDate.map(([date, sessions]) => (
                  <div key={date}>
                    <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                      {formatDate(date)}
                    </p>
                    <div className="mt-1">{sessions.map(sessionRow)}</div>
                  </div>
                ))}
              </div>
            </Card>
          </TabsContent>

          <TabsContent value="social" className="mt-4 space-y-4">
            <Card className="p-4">
              <h2 className="text-sm font-medium">Create a Social</h2>
              <p className="mt-1 text-[11px] text-muted-foreground">
                One Social per city and date. Both ticket types share the same event date.
              </p>
              <div className="mt-3 grid gap-3 sm:grid-cols-2">
                <div>
                  <Label className="text-xs">City</Label>
                  <select
                    value={socialCity}
                    onChange={(e) => setSocialCity(e.target.value)}
                    className="mt-1 h-9 w-full rounded-md border border-input bg-background px-2 text-sm"
                  >
                    {cities.map((city) => (
                      <option key={city.id} value={city.id}>
                        {city.name}
                      </option>
                    ))}
                  </select>
                </div>
                <div>
                  <Label className="text-xs">Date</Label>
                  <Input
                    type="date"
                    min={today}
                    value={socialDate}
                    onChange={(e) => setSocialDate(e.target.value)}
                    className="mt-1 h-9 text-sm"
                  />
                </div>
                <div>
                  <Label className="text-xs">Capacity (optional)</Label>
                  <Input
                    value={socialCapacity}
                    onChange={(e) => setSocialCapacity(e.target.value)}
                    placeholder="No limit"
                    inputMode="numeric"
                    className="mt-1 h-9 text-sm"
                  />
                </div>
                <div>
                  <Label className="text-xs">Ticket types</Label>
                  <div className="mt-2 space-y-2">
                    {(socialProduct?.variants ?? []).map((variant) => (
                      <label key={variant.variantId} className="flex items-center gap-2 text-sm">
                        <Checkbox
                          checked={socialVariants.includes(variant.variantId)}
                          onCheckedChange={() => toggleVariant(variant.variantId)}
                        />
                        <span>{variant.title}</span>
                      </label>
                    ))}
                    {!socialProduct && (
                      <p className="text-xs text-muted-foreground">Loading ticket types…</p>
                    )}
                  </div>
                </div>
              </div>
              <Button
                size="sm"
                className="mt-4 gap-1.5 text-xs"
                disabled={createSocial.isPending}
                onClick={submitSocial}
              >
                <CalendarPlus className="h-3 w-3" />
                Create occurrence
              </Button>
            </Card>

            <Card className="p-4">
              <h2 className="text-sm font-medium">Upcoming Socials</h2>
              {socials.length === 0 && (
                <p className="mt-2 text-xs text-muted-foreground">No upcoming Social dates.</p>
              )}
              <div className="mt-2 space-y-4">
                {socials.map((session) => (
                  <div key={session.id}>
                    <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                      {formatDate(session.date)}
                    </p>
                    {sessionRow(session)}
                  </div>
                ))}
              </div>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </PageLayout>
  );
};

export default AdminSchedule;
